### ISSUE TITLE
Cannot find entry file index.ios.js

### ISSUE THREAD

**Issue by japhar81** [cbrevik/react-native-typescript-starter#2]
Getting an error when I clone the repo, run npm install, and then do react-native run-ios;

![image](https://cloud.githubusercontent.com/assets/1619545/26810405/877f90b0-4a39-11e7-8f26-9995b65f71b5.png)

Packager complains;
```
error: bundling: Error
    at DependencyGraph._getAbsolutePath (/Users/hzektser/IdeaProjects/react-native-typescript-starter/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:280:11)
    at DependencyGraph.getDependencies (/Users/hzektser/IdeaProjects/react-native-typescript-starter/node_modules/react-native/packager/src/node-haste/DependencyGraph.js:218:26)
    at Resolver.getDependencies (/Users/hzektser/IdeaProjects/react-native-typescript-starter/node_modules/react-native/packager/src/Resolver/index.js:107:27)
    at /Users/hzektser/IdeaProjects/react-native-typescript-starter/node_modules/react-native/packager/src/Bundler/index.js:591:37
    at Generator.next (<anonymous>)
    at step (/Users/hzektser/IdeaProjects/react-native-typescript-starter/node_modules/react-native/packager/src/Bundler/index.js:12:445)
    at /Users/hzektser/IdeaProjects/react-native-typescript-starter/node_modules/react-native/packager/src/Bundler/index.js:12:605
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
Bundling `index.ios.js`  0.0% (0/1), failed.
```

**Comment by cbrevik** [comment]
Hi @japhar81. This usually happens to me when I have had another apps RN packager running. Could you try running `npm start -- --reset-cache` in the project instead?

**Comment by japhar81** [comment]
@cbrevik npm start actually works fine to fire up the packager, but that doesnt start the ios simulator/app.. Maybe I'm misunderstanding the intended workflow?

**Comment by cbrevik** [comment]
@japhar81 I meant run that to reset your RN packager cache, which can sometimes help if the RN packager has problems picking up files.

**Comment by japhar81** [comment]
Sorry, forgot to comment back -- nuking the cache did in fact do the trick.
